"""
Persistent AI/Prop-Firm Monitor
--------------------------------
Run separately from Streamlit so alerts can continue while the browser is closed.

Environment/config:
  prop_ai_monitor_config.json generated by the Streamlit app.

The service supports automatic EA PAPER execution and an optional generic LIVE broker webhook. LIVE execution requires your own authenticated broker/bridge endpoint.
"""
import json
import os
import time
import smtplib
from email.mime.text import MIMEText
from datetime import datetime

import pandas as pd
import yfinance as yf
import requests

CONFIG_PATH = os.getenv("PROP_AI_CONFIG", "prop_ai_monitor_config.json")

YF_TICKERS = {
    "Gold (XAU/USD)": "GC=F",
    "Bitcoin (BTC/USDT)": "BTC-USD",
    "NIFTY 50 Index": "^NSEI",
}

def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def calc_signal(df, asset, risk_pct):
    if len(df) < 30:
        return None
    close = df["Close"]
    ema9 = close.ewm(span=9, adjust=False).mean()
    ema21 = close.ewm(span=21, adjust=False).mean()
    last = float(close.iloc[-1])
    side = "LONG" if float(ema9.iloc[-1]) > float(ema21.iloc[-1]) else "SHORT"
    rng = (df["High"] - df["Low"]).rolling(14).mean().iloc[-1]
    rng = max(float(rng), last * 0.002)
    sl = last - 1.15*rng if side == "LONG" else last + 1.15*rng
    tp1 = last + (last-sl) if side == "LONG" else last - (sl-last)
    tp2 = last + 2*(last-sl) if side == "LONG" else last - 2*(sl-last)
    return {
        "asset": asset, "side": side, "entry": last, "sl": sl,
        "tp1": tp1, "tp2": tp2, "risk_pct": risk_pct,
        "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

def send_telegram(cfg, text):
    token, chat_id = cfg.get("telegram_bot_token"), cfg.get("telegram_chat_id")
    if not token or not chat_id:
        return False
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    r = requests.post(url, json={"chat_id": chat_id, "text": text}, timeout=15)
    r.raise_for_status()
    return True

def send_discord(cfg, text):
    webhook = cfg.get("discord_webhook")
    if not webhook:
        return False
    r = requests.post(webhook, json={"content": text}, timeout=15)
    r.raise_for_status()
    return True

def send_email(cfg, subject, body):
    host, user, password, recipient = (
        cfg.get("smtp_host"), cfg.get("smtp_user"),
        cfg.get("smtp_password"), cfg.get("alert_email")
    )
    if not all([host, user, password, recipient]):
        return False
    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = recipient
    with smtplib.SMTP(host, int(cfg.get("smtp_port", 587))) as server:
        server.starttls()
        server.login(user, password)
        server.sendmail(user, [recipient], msg.as_string())
    return True

def notify_all(cfg, message):
    results = {}
    for name, fn in [
        ("telegram", lambda: send_telegram(cfg, message)),
        ("discord", lambda: send_discord(cfg, message)),
        ("email", lambda: send_email(cfg, "Prop AI Signal", message)),
    ]:
        try:
            results[name] = fn()
        except Exception as exc:
            results[name] = f"error: {exc}"
    return results

def execute_ea(cfg, sig):
    """Automatically hand an approved signal to the EA execution layer.

    PAPER mode writes an execution record locally. LIVE mode POSTs a generic order
    payload to the user-supplied broker/bridge endpoint. The endpoint must perform
    its own authentication, symbol mapping, position sizing and broker validation.
    """
    if not cfg.get("auto_ea_on_signal", False):
        return {"status": "disabled"}
    if not cfg.get("risk_approved", True):
        return {"status": "blocked", "reason": "risk gate"}
    mode = str(cfg.get("ea_execution_mode", "PAPER")).upper()
    order = {
        "source": "Smart Session Anomaly Detector",
        "ea": "AI Signal EA",
        "asset": sig["asset"],
        "side": "BUY" if sig["side"] == "LONG" else "SELL",
        "entry": sig["entry"], "sl": sig["sl"],
        "tp1": sig["tp1"], "tp2": sig["tp2"],
        "risk_pct": sig["risk_pct"],
        "timestamp": sig["time"],
    }
    if mode == "PAPER":
        with open("ea_trade_log.jsonl", "a", encoding="utf-8") as f:
            f.write(json.dumps({**order, "mode": "PAPER", "status": "EXECUTED"}) + "\n")
        return {"status": "executed", "mode": "PAPER"}
    endpoint = cfg.get("broker_api_endpoint")
    if not endpoint:
        return {"status": "blocked", "reason": "No LIVE broker endpoint configured"}
    r = requests.post(endpoint, json=order, timeout=15)
    r.raise_for_status()
    return {"status": "executed", "mode": "LIVE", "response": r.text[:300]}

def main():
    print("Prop AI Monitor started. EA auto-execution supports PAPER mode and optional LIVE broker webhook.")
    last_sent = {}
    while True:
        cfg = load_config()
        if not cfg.get("enabled"):
            time.sleep(30)
            continue
        for asset in cfg.get("assets", list(YF_TICKERS)):
            ticker = YF_TICKERS.get(asset)
            if not ticker:
                continue
            try:
                df = yf.download(ticker, period="5d", interval="15m", progress=False, auto_adjust=False)
                if isinstance(df.columns, pd.MultiIndex):
                    df.columns = df.columns.get_level_values(0)
                df = df.dropna()
                sig = calc_signal(df, asset, float(cfg.get("max_trade_risk_pct", 0.5)))
                if not sig:
                    continue
                sig["risk_approved"] = float(sig["risk_pct"]) <= float(cfg.get("max_trade_risk_pct", 0.5))
                if not sig["risk_approved"]:
                    continue
                    continue
                key = f"{asset}:{sig['side']}:{round(sig['entry'], 2)}"
                # Prevent repeated notifications for the same setup for 30 minutes.
                if key in last_sent and time.time() - last_sent[key] < 1800:
                    continue
                msg = (
                    f"🧸 Prop AI Signal\n{asset} {sig['side']}\n"
                    f"Entry: {sig['entry']:.2f}\nSL: {sig['sl']:.2f}\n"
                    f"TP1: {sig['tp1']:.2f}\nTP2: {sig['tp2']:.2f}\n"
                    f"Risk setting: {sig['risk_pct']:.2f}%\n"
                    f"Time: {sig['time']}\n\n"
                    "Signal only. Verify the configured account rules before execution."
                )
                results = notify_all(cfg, msg)
                exec_result = execute_ea(cfg, sig)
                if exec_result.get("status") == "executed":
                    results["ea"] = exec_result
                    msg += f"\n\n🤖 EA: {exec_result.get("mode", "EXECUTED")} trade triggered."
                    notify_all(cfg, msg)
                else:
                    results["ea"] = exec_result
                print(asset, results)
                last_sent[key] = time.time()
            except Exception as exc:
                print(f"{asset}: {exc}")
        time.sleep(int(cfg.get("interval_seconds", 60)))

if __name__ == "__main__":
    main()
